version: '3.5'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        networks:
            - IntegrationService
        ports:
            - '5432:5432'

    api:

        restart: always
        build:
          dockerfile: Dockerfile
          context: ./

        environment:
          - PGUSER=postgres
          - PGHOST=postgres
          - PGDATABASE=postgres
          - PGPASSWORD=postgres
          - PGPORT=5432
        networks:
          - IntegrationService
        ports:
          - '8080:8080'
networks:
  IntegrationService:
    # Use a custom driver
    name: IntegrationService
    driver: bridge