// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repo struct {
	GitTagsUrl           string               `protobuf:"bytes,1,opt,name=git_tags_url,json=gitTagsUrl,proto3" json:"git_tags_url,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Private              bool                 `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	LanguagesUrl         string               `protobuf:"bytes,4,opt,name=languages_url,json=languagesUrl,proto3" json:"languages_url,omitempty"`
	StargazersUrl        string               `protobuf:"bytes,5,opt,name=stargazers_url,json=stargazersUrl,proto3" json:"stargazers_url,omitempty"`
	CommitsUrl           string               `protobuf:"bytes,6,opt,name=commits_url,json=commitsUrl,proto3" json:"commits_url,omitempty"`
	RepoCreatedAt        *timestamp.Timestamp `protobuf:"bytes,7,opt,name=repo_created_at,json=repoCreatedAt,proto3" json:"repo_created_at,omitempty"`
	RepoUpdatedAt        *timestamp.Timestamp `protobuf:"bytes,8,opt,name=repo_updated_at,json=repoUpdatedAt,proto3" json:"repo_updated_at,omitempty"`
	HomePage             string               `protobuf:"bytes,9,opt,name=home_page,json=homePage,proto3" json:"home_page,omitempty"`
	StargazersCount      int32                `protobuf:"varint,10,opt,name=stargazers_count,json=stargazersCount,proto3" json:"stargazers_count,omitempty"`
	LabelsUrl            string               `protobuf:"bytes,11,opt,name=labels_url,json=labelsUrl,proto3" json:"labels_url,omitempty"`
	Language             string               `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	Watchers             int32                `protobuf:"varint,13,opt,name=watchers,proto3" json:"watchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (m *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(m, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetGitTagsUrl() string {
	if m != nil {
		return m.GitTagsUrl
	}
	return ""
}

func (m *Repo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Repo) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *Repo) GetLanguagesUrl() string {
	if m != nil {
		return m.LanguagesUrl
	}
	return ""
}

func (m *Repo) GetStargazersUrl() string {
	if m != nil {
		return m.StargazersUrl
	}
	return ""
}

func (m *Repo) GetCommitsUrl() string {
	if m != nil {
		return m.CommitsUrl
	}
	return ""
}

func (m *Repo) GetRepoCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RepoCreatedAt
	}
	return nil
}

func (m *Repo) GetRepoUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RepoUpdatedAt
	}
	return nil
}

func (m *Repo) GetHomePage() string {
	if m != nil {
		return m.HomePage
	}
	return ""
}

func (m *Repo) GetStargazersCount() int32 {
	if m != nil {
		return m.StargazersCount
	}
	return 0
}

func (m *Repo) GetLabelsUrl() string {
	if m != nil {
		return m.LabelsUrl
	}
	return ""
}

func (m *Repo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Repo) GetWatchers() int32 {
	if m != nil {
		return m.Watchers
	}
	return 0
}

type GithubRepoListResponse struct {
	Repos                []*Repo  `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepoListResponse) Reset()         { *m = GithubRepoListResponse{} }
func (m *GithubRepoListResponse) String() string { return proto.CompactTextString(m) }
func (*GithubRepoListResponse) ProtoMessage()    {}
func (*GithubRepoListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GithubRepoListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepoListResponse.Unmarshal(m, b)
}
func (m *GithubRepoListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepoListResponse.Marshal(b, m, deterministic)
}
func (m *GithubRepoListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepoListResponse.Merge(m, src)
}
func (m *GithubRepoListResponse) XXX_Size() int {
	return xxx_messageInfo_GithubRepoListResponse.Size(m)
}
func (m *GithubRepoListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepoListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepoListResponse proto.InternalMessageInfo

func (m *GithubRepoListResponse) GetRepos() []*Repo {
	if m != nil {
		return m.Repos
	}
	return nil
}

type GithubRepoListRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepoListRequest) Reset()         { *m = GithubRepoListRequest{} }
func (m *GithubRepoListRequest) String() string { return proto.CompactTextString(m) }
func (*GithubRepoListRequest) ProtoMessage()    {}
func (*GithubRepoListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GithubRepoListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepoListRequest.Unmarshal(m, b)
}
func (m *GithubRepoListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepoListRequest.Marshal(b, m, deterministic)
}
func (m *GithubRepoListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepoListRequest.Merge(m, src)
}
func (m *GithubRepoListRequest) XXX_Size() int {
	return xxx_messageInfo_GithubRepoListRequest.Size(m)
}
func (m *GithubRepoListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepoListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepoListRequest proto.InternalMessageInfo

func (m *GithubRepoListRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LanguagesRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LanguagesRequest) Reset()         { *m = LanguagesRequest{} }
func (m *LanguagesRequest) String() string { return proto.CompactTextString(m) }
func (*LanguagesRequest) ProtoMessage()    {}
func (*LanguagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LanguagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LanguagesRequest.Unmarshal(m, b)
}
func (m *LanguagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LanguagesRequest.Marshal(b, m, deterministic)
}
func (m *LanguagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LanguagesRequest.Merge(m, src)
}
func (m *LanguagesRequest) XXX_Size() int {
	return xxx_messageInfo_LanguagesRequest.Size(m)
}
func (m *LanguagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LanguagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LanguagesRequest proto.InternalMessageInfo

func (m *LanguagesRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LanguagesResponse struct {
	Language             []string `protobuf:"bytes,1,rep,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LanguagesResponse) Reset()         { *m = LanguagesResponse{} }
func (m *LanguagesResponse) String() string { return proto.CompactTextString(m) }
func (*LanguagesResponse) ProtoMessage()    {}
func (*LanguagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LanguagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LanguagesResponse.Unmarshal(m, b)
}
func (m *LanguagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LanguagesResponse.Marshal(b, m, deterministic)
}
func (m *LanguagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LanguagesResponse.Merge(m, src)
}
func (m *LanguagesResponse) XXX_Size() int {
	return xxx_messageInfo_LanguagesResponse.Size(m)
}
func (m *LanguagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LanguagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LanguagesResponse proto.InternalMessageInfo

func (m *LanguagesResponse) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

type UserGithubBasicRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGithubBasicRequest) Reset()         { *m = UserGithubBasicRequest{} }
func (m *UserGithubBasicRequest) String() string { return proto.CompactTextString(m) }
func (*UserGithubBasicRequest) ProtoMessage()    {}
func (*UserGithubBasicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserGithubBasicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGithubBasicRequest.Unmarshal(m, b)
}
func (m *UserGithubBasicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGithubBasicRequest.Marshal(b, m, deterministic)
}
func (m *UserGithubBasicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGithubBasicRequest.Merge(m, src)
}
func (m *UserGithubBasicRequest) XXX_Size() int {
	return xxx_messageInfo_UserGithubBasicRequest.Size(m)
}
func (m *UserGithubBasicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGithubBasicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGithubBasicRequest proto.InternalMessageInfo

func (m *UserGithubBasicRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserGithubBasicResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Company              string   `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	ReposUrl             string   `protobuf:"bytes,7,opt,name=repos_url,json=reposUrl,proto3" json:"repos_url,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Location             string   `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	PublicRepos          int32    `protobuf:"varint,10,opt,name=public_repos,json=publicRepos,proto3" json:"public_repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGithubBasicResponse) Reset()         { *m = UserGithubBasicResponse{} }
func (m *UserGithubBasicResponse) String() string { return proto.CompactTextString(m) }
func (*UserGithubBasicResponse) ProtoMessage()    {}
func (*UserGithubBasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserGithubBasicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGithubBasicResponse.Unmarshal(m, b)
}
func (m *UserGithubBasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGithubBasicResponse.Marshal(b, m, deterministic)
}
func (m *UserGithubBasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGithubBasicResponse.Merge(m, src)
}
func (m *UserGithubBasicResponse) XXX_Size() int {
	return xxx_messageInfo_UserGithubBasicResponse.Size(m)
}
func (m *UserGithubBasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGithubBasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGithubBasicResponse proto.InternalMessageInfo

func (m *UserGithubBasicResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGithubBasicResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserGithubBasicResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UserGithubBasicResponse) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *UserGithubBasicResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserGithubBasicResponse) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *UserGithubBasicResponse) GetReposUrl() string {
	if m != nil {
		return m.ReposUrl
	}
	return ""
}

func (m *UserGithubBasicResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserGithubBasicResponse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UserGithubBasicResponse) GetPublicRepos() int32 {
	if m != nil {
		return m.PublicRepos
	}
	return 0
}

type UserHasTokenRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHasTokenRequest) Reset()         { *m = UserHasTokenRequest{} }
func (m *UserHasTokenRequest) String() string { return proto.CompactTextString(m) }
func (*UserHasTokenRequest) ProtoMessage()    {}
func (*UserHasTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserHasTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHasTokenRequest.Unmarshal(m, b)
}
func (m *UserHasTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHasTokenRequest.Marshal(b, m, deterministic)
}
func (m *UserHasTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHasTokenRequest.Merge(m, src)
}
func (m *UserHasTokenRequest) XXX_Size() int {
	return xxx_messageInfo_UserHasTokenRequest.Size(m)
}
func (m *UserHasTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHasTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserHasTokenRequest proto.InternalMessageInfo

func (m *UserHasTokenRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserHasTokenResponse struct {
	HasToken             bool     `protobuf:"varint,1,opt,name=has_token,json=hasToken,proto3" json:"has_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHasTokenResponse) Reset()         { *m = UserHasTokenResponse{} }
func (m *UserHasTokenResponse) String() string { return proto.CompactTextString(m) }
func (*UserHasTokenResponse) ProtoMessage()    {}
func (*UserHasTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserHasTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHasTokenResponse.Unmarshal(m, b)
}
func (m *UserHasTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHasTokenResponse.Marshal(b, m, deterministic)
}
func (m *UserHasTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHasTokenResponse.Merge(m, src)
}
func (m *UserHasTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UserHasTokenResponse.Size(m)
}
func (m *UserHasTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHasTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserHasTokenResponse proto.InternalMessageInfo

func (m *UserHasTokenResponse) GetHasToken() bool {
	if m != nil {
		return m.HasToken
	}
	return false
}

func init() {
	proto.RegisterType((*Repo)(nil), "user.Repo")
	proto.RegisterType((*GithubRepoListResponse)(nil), "user.GithubRepoListResponse")
	proto.RegisterType((*GithubRepoListRequest)(nil), "user.GithubRepoListRequest")
	proto.RegisterType((*LanguagesRequest)(nil), "user.LanguagesRequest")
	proto.RegisterType((*LanguagesResponse)(nil), "user.LanguagesResponse")
	proto.RegisterType((*UserGithubBasicRequest)(nil), "user.UserGithubBasicRequest")
	proto.RegisterType((*UserGithubBasicResponse)(nil), "user.UserGithubBasicResponse")
	proto.RegisterType((*UserHasTokenRequest)(nil), "user.UserHasTokenRequest")
	proto.RegisterType((*UserHasTokenResponse)(nil), "user.UserHasTokenResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0xfd, 0xe5, 0x1f, 0x24, 0x93, 0x04, 0xf2, 0xdb, 0x52, 0x70, 0x0d, 0x08, 0xd7, 0x15, 0x6a,
	0x7a, 0x09, 0x12, 0xdc, 0x7a, 0x03, 0x0e, 0x69, 0x25, 0x5a, 0x21, 0x17, 0x2e, 0xbd, 0x44, 0x1b,
	0x67, 0x71, 0x56, 0xb5, 0xbd, 0xee, 0xee, 0x9a, 0xaa, 0xfd, 0x1c, 0xfd, 0x46, 0xfd, 0x52, 0x3d,
	0x56, 0xb3, 0x6b, 0x3b, 0x2e, 0x04, 0xa9, 0x37, 0xcf, 0xdb, 0x37, 0x6f, 0x76, 0x66, 0xde, 0x1a,
	0x20, 0x57, 0x4c, 0x4e, 0x32, 0x29, 0xb4, 0x20, 0x6d, 0xfc, 0x76, 0x8f, 0x22, 0x21, 0xa2, 0x98,
	0x9d, 0x18, 0x6c, 0x9e, 0xdf, 0x9d, 0x68, 0x9e, 0x30, 0xa5, 0x69, 0x92, 0x59, 0x9a, 0xff, 0xbb,
	0x05, 0xed, 0x80, 0x65, 0x82, 0x78, 0x30, 0x88, 0xb8, 0x9e, 0x69, 0x1a, 0xa9, 0x59, 0x2e, 0x63,
	0xa7, 0xe1, 0x35, 0xc6, 0xbd, 0x00, 0x22, 0xae, 0x6f, 0x68, 0xa4, 0x6e, 0x65, 0x4c, 0x3c, 0xe8,
	0x2f, 0x98, 0x0a, 0x25, 0xcf, 0x34, 0x17, 0xa9, 0xd3, 0x34, 0x84, 0x3a, 0x44, 0x1c, 0xd8, 0xcc,
	0x24, 0xbf, 0xa7, 0x9a, 0x39, 0x2d, 0xaf, 0x31, 0xee, 0x06, 0x65, 0x48, 0x5e, 0xc1, 0x30, 0xa6,
	0x69, 0x94, 0xd3, 0x88, 0x59, 0xf9, 0xb6, 0xc9, 0x1e, 0x54, 0x20, 0x16, 0x38, 0x86, 0x2d, 0xa5,
	0xa9, 0x8c, 0xe8, 0x0f, 0x26, 0x2d, 0xab, 0x63, 0x58, 0xc3, 0x15, 0x8a, 0xb4, 0x23, 0xe8, 0x87,
	0x22, 0x49, 0xb8, 0xb6, 0x9c, 0x0d, 0x7b, 0xd1, 0x02, 0x42, 0xc2, 0x05, 0x6c, 0x4b, 0x96, 0x89,
	0x59, 0x28, 0x19, 0xd5, 0x6c, 0x31, 0xa3, 0xda, 0xd9, 0xf4, 0x1a, 0xe3, 0xfe, 0xa9, 0x3b, 0xb1,
	0xe3, 0x98, 0x94, 0xe3, 0x98, 0xdc, 0x94, 0xe3, 0x08, 0x86, 0x98, 0x72, 0x69, 0x33, 0xce, 0x75,
	0xa5, 0x91, 0x67, 0x8b, 0x52, 0xa3, 0xfb, 0x6f, 0x1a, 0xb7, 0x36, 0xe3, 0x5c, 0x93, 0x7d, 0xe8,
	0x2d, 0x45, 0xc2, 0x66, 0x19, 0x8d, 0x98, 0xd3, 0x33, 0xd7, 0xec, 0x22, 0x70, 0x4d, 0x23, 0x46,
	0xde, 0xc0, 0xa8, 0xd6, 0x6c, 0x28, 0xf2, 0x54, 0x3b, 0xe0, 0x35, 0xc6, 0x9d, 0x60, 0x7b, 0x85,
	0x5f, 0x22, 0x4c, 0x0e, 0x01, 0x62, 0x3a, 0x67, 0xb1, 0xed, 0xb7, 0x6f, 0x84, 0x7a, 0x16, 0xc1,
	0x76, 0x5d, 0xe8, 0x96, 0x63, 0x74, 0x06, 0xb6, 0x4a, 0x19, 0xe3, 0xd9, 0x37, 0xaa, 0xc3, 0x25,
	0x93, 0xca, 0x19, 0x1a, 0xf5, 0x2a, 0xf6, 0xdf, 0xc2, 0xee, 0x94, 0xeb, 0x65, 0x3e, 0xc7, 0xfd,
	0x5f, 0x71, 0xa5, 0x03, 0xa6, 0x32, 0x91, 0x2a, 0x46, 0x3c, 0xe8, 0x60, 0x27, 0xca, 0x69, 0x78,
	0xad, 0x71, 0xff, 0x14, 0x26, 0xc6, 0x57, 0x48, 0x0b, 0xec, 0x81, 0xff, 0x1a, 0x9e, 0x3f, 0xcc,
	0xfd, 0x9a, 0x33, 0xa5, 0xc9, 0x16, 0x34, 0xf9, 0xc2, 0x98, 0xa7, 0x1d, 0x34, 0xf9, 0xc2, 0xf7,
	0x61, 0x74, 0x55, 0xee, 0xf8, 0x29, 0xce, 0x09, 0xfc, 0x5f, 0xe3, 0x14, 0x77, 0xa8, 0x77, 0x85,
	0xd7, 0xa8, 0x75, 0xe5, 0x8f, 0x61, 0xf7, 0x56, 0x31, 0x69, 0x6f, 0x70, 0x41, 0x15, 0x0f, 0x9f,
	0x92, 0xfe, 0xd9, 0x84, 0xbd, 0x47, 0xd4, 0xa2, 0xc2, 0x8a, 0xdb, 0x42, 0x2e, 0x56, 0xc4, 0x3e,
	0x53, 0x9a, 0xb0, 0xc2, 0xdc, 0x55, 0x4c, 0x46, 0xd0, 0xc2, 0xd9, 0xb7, 0x0c, 0x8c, 0x9f, 0xb8,
	0x14, 0x7a, 0x4f, 0x35, 0x95, 0x35, 0x3b, 0xf7, 0x2c, 0x82, 0x4b, 0x19, 0x41, 0x6b, 0xce, 0x45,
	0x61, 0x60, 0xfc, 0xc4, 0xc7, 0x11, 0x8a, 0x24, 0xa3, 0xe9, 0xf7, 0xc2, 0xb2, 0x65, 0x88, 0x3e,
	0x31, 0x53, 0x35, 0x4a, 0x9b, 0xb6, 0xb2, 0x01, 0x50, 0x68, 0x07, 0x3a, 0x2c, 0xa1, 0x3c, 0x36,
	0xf6, 0xeb, 0x05, 0x36, 0x30, 0xd3, 0x11, 0x21, 0x35, 0x0f, 0xb1, 0x70, 0x56, 0x19, 0x93, 0x97,
	0x30, 0xc8, 0xf2, 0x79, 0xcc, 0xc3, 0x99, 0x5d, 0xa2, 0x75, 0x55, 0xdf, 0x62, 0x81, 0x59, 0xdf,
	0x31, 0x3c, 0xc3, 0xa9, 0xbc, 0xa3, 0xea, 0x46, 0x7c, 0x61, 0xe9, 0xe3, 0xe9, 0x99, 0x89, 0xf8,
	0x67, 0xb0, 0xf3, 0x37, 0xad, 0x98, 0x1c, 0x1a, 0x9b, 0xaa, 0x99, 0x46, 0xd0, 0xd0, 0xbb, 0x41,
	0x77, 0x59, 0x90, 0x4e, 0x7f, 0x35, 0xa1, 0x8f, 0x59, 0x9f, 0x98, 0xbc, 0xe7, 0x21, 0x23, 0x1f,
	0x61, 0x38, 0x65, 0xda, 0x2e, 0xe0, 0x7d, 0x7a, 0x27, 0xc8, 0x81, 0xb5, 0xd3, 0xfa, 0x0d, 0xba,
	0x87, 0x4f, 0x9c, 0xda, 0xd2, 0xfe, 0x7f, 0xe4, 0x03, 0x6c, 0x55, 0x7a, 0xa6, 0x1b, 0xb2, 0x6f,
	0x53, 0xd6, 0x1a, 0xd2, 0x3d, 0x58, 0x7f, 0x58, 0xc9, 0x4d, 0x61, 0x50, 0xef, 0x91, 0xbc, 0x58,
	0xd5, 0x7f, 0x30, 0x1e, 0xd7, 0x5d, 0x77, 0x54, 0x09, 0x5d, 0xc1, 0xde, 0x94, 0xe9, 0x6b, 0x29,
	0x22, 0x49, 0x93, 0x84, 0xa7, 0x51, 0xe5, 0x69, 0xb2, 0x6b, 0x13, 0x1f, 0x3e, 0x04, 0x77, 0xef,
	0x11, 0x5e, 0xaa, 0x5d, 0x74, 0x3f, 0x6f, 0xe0, 0x59, 0x36, 0x9f, 0x6f, 0x98, 0x1f, 0xcd, 0xd9,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xf1, 0xbb, 0x6b, 0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetGithubInfo(ctx context.Context, in *UserGithubBasicRequest, opts ...grpc.CallOption) (*UserGithubBasicResponse, error)
	GetGithubRepos(ctx context.Context, in *GithubRepoListRequest, opts ...grpc.CallOption) (*GithubRepoListResponse, error)
	UserHasToken(ctx context.Context, in *UserHasTokenRequest, opts ...grpc.CallOption) (*UserHasTokenResponse, error)
	GetProgrammingLanguages(ctx context.Context, in *LanguagesRequest, opts ...grpc.CallOption) (*LanguagesResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetGithubInfo(ctx context.Context, in *UserGithubBasicRequest, opts ...grpc.CallOption) (*UserGithubBasicResponse, error) {
	out := new(UserGithubBasicResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetGithubInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGithubRepos(ctx context.Context, in *GithubRepoListRequest, opts ...grpc.CallOption) (*GithubRepoListResponse, error) {
	out := new(GithubRepoListResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetGithubRepos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserHasToken(ctx context.Context, in *UserHasTokenRequest, opts ...grpc.CallOption) (*UserHasTokenResponse, error) {
	out := new(UserHasTokenResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserHasToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProgrammingLanguages(ctx context.Context, in *LanguagesRequest, opts ...grpc.CallOption) (*LanguagesResponse, error) {
	out := new(LanguagesResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetProgrammingLanguages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetGithubInfo(context.Context, *UserGithubBasicRequest) (*UserGithubBasicResponse, error)
	GetGithubRepos(context.Context, *GithubRepoListRequest) (*GithubRepoListResponse, error)
	UserHasToken(context.Context, *UserHasTokenRequest) (*UserHasTokenResponse, error)
	GetProgrammingLanguages(context.Context, *LanguagesRequest) (*LanguagesResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetGithubInfo(ctx context.Context, req *UserGithubBasicRequest) (*UserGithubBasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGithubInfo not implemented")
}
func (*UnimplementedUserServiceServer) GetGithubRepos(ctx context.Context, req *GithubRepoListRequest) (*GithubRepoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGithubRepos not implemented")
}
func (*UnimplementedUserServiceServer) UserHasToken(ctx context.Context, req *UserHasTokenRequest) (*UserHasTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserHasToken not implemented")
}
func (*UnimplementedUserServiceServer) GetProgrammingLanguages(ctx context.Context, req *LanguagesRequest) (*LanguagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgrammingLanguages not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetGithubInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGithubBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGithubInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetGithubInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGithubInfo(ctx, req.(*UserGithubBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGithubRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GithubRepoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGithubRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetGithubRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGithubRepos(ctx, req.(*GithubRepoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserHasToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserHasTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserHasToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserHasToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserHasToken(ctx, req.(*UserHasTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProgrammingLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProgrammingLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetProgrammingLanguages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProgrammingLanguages(ctx, req.(*LanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGithubInfo",
			Handler:    _UserService_GetGithubInfo_Handler,
		},
		{
			MethodName: "GetGithubRepos",
			Handler:    _UserService_GetGithubRepos_Handler,
		},
		{
			MethodName: "UserHasToken",
			Handler:    _UserService_UserHasToken_Handler,
		},
		{
			MethodName: "GetProgrammingLanguages",
			Handler:    _UserService_GetProgrammingLanguages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
